/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaz;

import com.github.cliftonlabs.json_simple.JsonObject;
import com.github.cliftonlabs.json_simple.Jsoner;
import static interfaz.Borrar_Reserva.fondo;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.net.Socket;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class Borrar_Reclamacion extends javax.swing.JFrame implements ActionListener{

    /**
     * Creates new form Borrar_Reclamacion
     */
    public Borrar_Reclamacion() {
        initComponents();
        
        ImageIcon fondoP = new ImageIcon("src/fondoAPP.png");
        fondo1.setIcon(fondoP);

        ImageIcon vol = new ImageIcon("src/volver.png");
        volver1.setIcon(vol);
        volver1.setBorder(BorderFactory.createEmptyBorder());
        volver1.setBackground(new Color(0, 0, 0, 0));
        volver1.addActionListener(this);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jLabel1 = new javax.swing.JLabel();
        borrar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        dniF = new javax.swing.JTextField();
        idReserva = new javax.swing.JTextField();
        volver = new javax.swing.JButton();
        fondo = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        borrar1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        dni = new javax.swing.JTextField();
        idReclamacion = new javax.swing.JTextField();
        volver1 = new javax.swing.JButton();
        fondo1 = new javax.swing.JLabel();

        jFrame1.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        jFrame1.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        jLabel1.setText("BORRAR RESERVA");
        jFrame1.getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 240, -1));

        borrar.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        borrar.setText("BORRAR");
        borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarActionPerformed(evt);
            }
        });
        jFrame1.getContentPane().add(borrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, 120, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel2.setText("Introduce tu DNI:");
        jFrame1.getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel3.setText("Introduce el id de la reserva:");
        jFrame1.getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));
        jFrame1.getContentPane().add(dniF, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 90, -1));
        jFrame1.getContentPane().add(idReserva, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 90, -1));
        jFrame1.getContentPane().add(volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 40));
        jFrame1.getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        jLabel4.setText("BORRAR RECLAMACION");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 310, -1));

        borrar1.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        borrar1.setText("BORRAR");
        borrar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrar1ActionPerformed(evt);
            }
        });
        getContentPane().add(borrar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, 120, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel5.setText("Introduce tu DNI:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel6.setText("Introduce el id de la reclamación:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));
        getContentPane().add(dni, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 90, -1));
        getContentPane().add(idReclamacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 90, -1));
        getContentPane().add(volver1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 40));
        getContentPane().add(fondo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void borrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarActionPerformed

    }//GEN-LAST:event_borrarActionPerformed

    private void borrar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrar1ActionPerformed

        String mensaje = "";
        Socket cliente;
        try {
            cliente = new Socket("localhost",5555);
            DataInputStream dis = new DataInputStream(cliente.getInputStream()); 
            DataOutputStream dos = new DataOutputStream(cliente.getOutputStream()); 
            ObjectInputStream ois = new ObjectInputStream(cliente.getInputStream());
            ObjectOutputStream oos = new ObjectOutputStream(cliente.getOutputStream());
            
            dos.writeUTF("borrar_reclamacion");
            JsonObject jso = new JsonObject();
            Jsoner.serialize(jso);
            jso.put("dni", dni.getText());
            jso.put("id", idReclamacion.getText());
            
            oos.writeObject(jso);
            
            mensaje=dis.readUTF();
            
            cliente.close();
            
        } catch (IOException ex) {
            Logger.getLogger(Insertar_Reclamacion.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        JOptionPane.showMessageDialog(this, mensaje);
        
        
    }//GEN-LAST:event_borrar1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Borrar_Reclamacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Borrar_Reclamacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Borrar_Reclamacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Borrar_Reclamacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Borrar_Reclamacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton borrar;
    public static javax.swing.JButton borrar1;
    public static javax.swing.JTextField dni;
    public static javax.swing.JTextField dniF;
    public static javax.swing.JLabel fondo;
    public static javax.swing.JLabel fondo1;
    public static javax.swing.JTextField idReclamacion;
    public static javax.swing.JTextField idReserva;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JButton volver;
    private javax.swing.JButton volver1;
    // End of variables declaration//GEN-END:variables

    public void actionPerformed(ActionEvent e) {
        if(e.getSource()==volver1){
            try {
                Pantalla_Principal p = new Pantalla_Principal();
                p.setVisible(true);
                this.setVisible(false);
                
            } catch (SQLException ex) {
            } catch (IOException ex) {
                Logger.getLogger(Borrar_Reclamacion.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
    }
}
