/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaz;

import com.github.cliftonlabs.json_simple.JsonObject;
import com.github.cliftonlabs.json_simple.Jsoner;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.net.Socket;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import static org.mariadb.jdbc.internal.io.socket.UnixDomainSocket.socket;

/**
 *
 * @author Admin
 */
public class Iniciar_Sesion extends javax.swing.JFrame {

    /**
     * Creates new form Iniciar_Sesion
     */
    
    String dni_Usuario;
    Socket cliente;
    public Iniciar_Sesion() throws SQLException, IOException {
        initComponents();
        ImageIcon fondo1 = new ImageIcon("src/fondoAPP.png");
        fondo.setIcon(fondo1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        telefonoT = new javax.swing.JTextField();
        nombreT = new javax.swing.JTextField();
        apellidoT = new javax.swing.JTextField();
        dniT = new javax.swing.JTextField();
        iniciar = new javax.swing.JButton();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel2.setText("Nombre:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, -1, -1));

        jLabel3.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel3.setText("Apellido:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, -1));

        jLabel4.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel4.setText("DNI:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, -1));

        jLabel5.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel5.setText("Telefono:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, -1, -1));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("INTRODUCE TUS DATOS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, -1, -1));
        getContentPane().add(telefonoT, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, 80, -1));
        getContentPane().add(nombreT, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 80, -1));
        getContentPane().add(apellidoT, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 80, -1));
        getContentPane().add(dniT, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 80, -1));

        iniciar.setBackground(new java.awt.Color(0, 0, 0));
        iniciar.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        iniciar.setForeground(new java.awt.Color(255, 255, 255));
        iniciar.setText("INICIAR SESIÓN");
        iniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iniciarActionPerformed(evt);
            }
        });
        getContentPane().add(iniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, -1, -1));
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void iniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iniciarActionPerformed
        try {
            cliente = new Socket("localhost",5555);
            //DataInputStream dis = new DataInputStream(cliente.getInputStream()); 
            DataOutputStream dos = new DataOutputStream(cliente.getOutputStream()); 
            ObjectOutputStream oos = new ObjectOutputStream(cliente.getOutputStream());
            //ObjectInputStream ois = new ObjectInputStream(cliente.getInputStream());
                
                dos.writeUTF("insertar_cliente");
                JsonObject jsoLL = new JsonObject();
                
                Jsoner.serialize(jsoLL);
                jsoLL.put("nombre", nombreT.getText());
                jsoLL.put("apellido", apellidoT.getText());
                jsoLL.put("dni", dniT.getText());
                jsoLL.put("tel", telefonoT.getText());
                oos.writeObject(jsoLL);
                
                JOptionPane.showMessageDialog(this, "Si el usuario no exite se creara.\nTus datos seran almacenados en la base de datos.");
                
                
                
                
                cliente.close();
                
                Pantalla_Principal principal;
                principal = new Pantalla_Principal();
                
                principal.dni_Usuario=dniT.getText();
                this.setVisible(false);
                principal.setVisible(true);
                
                
        } catch (IOException ex) {
            Logger.getLogger(Iniciar_Sesion.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Iniciar_Sesion.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_iniciarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Iniciar_Sesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Iniciar_Sesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Iniciar_Sesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Iniciar_Sesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Iniciar_Sesion().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(Iniciar_Sesion.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IOException ex) {
                    Logger.getLogger(Iniciar_Sesion.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField apellidoT;
    private javax.swing.JTextField dniT;
    private javax.swing.JLabel fondo;
    private javax.swing.JButton iniciar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField nombreT;
    private javax.swing.JTextField telefonoT;
    // End of variables declaration//GEN-END:variables
}
