/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaz;

import com.github.cliftonlabs.json_simple.JsonObject;
import java.awt.Color;
import java.awt.GridLayout;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.net.MalformedURLException;
import java.net.Socket;
import java.net.URL;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import static org.mariadb.jdbc.internal.io.socket.UnixDomainSocket.socket;

/**
 *
 * @author Admin
 */
public class Pantalla_Principal extends javax.swing.JFrame implements ActionListener {

    /**
     * Creates new form Pantalla_Principal
     */
   //Busqueda buscador;
    
    Image fotoHotel;
    String dni_Usuario;
    Socket cliente;
    public Pantalla_Principal() throws SQLException, IOException {
        initComponents();
        
        
        ImageIcon fondo1 = new ImageIcon("src/fondoAPP.png");
        fondo.setIcon(fondo1);
        
        ImageIcon ubi = new ImageIcon("src/ubicacion.png");
        ubicacion.setIcon(ubi);
        
        imagen.setVisible(false);
        nombreHotel.setVisible(false);
        cp.setVisible(false);
        reservar.setVisible(false);
        nombreL.setVisible(false);
        cpL.setVisible(false);
        ubicacion.setVisible(false);
        ubicacionReal.setVisible(false);
       
        reservar.setOpaque(false);
        reservar.setBackground(new Color(0,0,0,6));
        reservar.setBorder(null);
        
        reservar.addActionListener(this);
        busqueda.buscar.addActionListener(this);
        busqueda.buscarVoz.addActionListener(this);
        
        borrarReserva.addActionListener(this);
        modReserva.addActionListener(this);
        insertReclamacion.addActionListener(this);
        ver_personal.addActionListener(this);
        ver_reclamaciones.addActionListener(this);
        ver_reservas.addActionListener(this);
        borrar_reclamacion.addActionListener(this);
        insertar_mantenimiento1.addActionListener(this);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        nombreHotel = new javax.swing.JLabel();
        reservar = new javax.swing.JButton();
        cp = new javax.swing.JLabel();
        imagen = new javax.swing.JLabel();
        cpL = new javax.swing.JLabel();
        nombreL = new javax.swing.JLabel();
        ubicacion = new javax.swing.JLabel();
        ubicacionReal = new javax.swing.JLabel();
        busqueda = new interfaz.Busqueda();
        fondo = new javax.swing.JLabel();
        barraMenu = new javax.swing.JMenuBar();
        menuBorrar = new javax.swing.JMenu();
        borrarReserva = new javax.swing.JMenuItem();
        borrar_reclamacion = new javax.swing.JMenuItem();
        menuMod = new javax.swing.JMenu();
        modReserva = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        ver_reservas = new javax.swing.JMenuItem();
        ver_personal = new javax.swing.JMenuItem();
        ver_reclamaciones = new javax.swing.JMenuItem();
        insertar_mantenimiento = new javax.swing.JMenu();
        insertReclamacion = new javax.swing.JMenuItem();
        insertar_mantenimiento1 = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(600, 400));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nombreHotel.setFont(new java.awt.Font("Segoe UI", 3, 21)); // NOI18N
        nombreHotel.setText("y");
        getContentPane().add(nombreHotel, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 140, 120, 40));

        reservar.setBackground(new java.awt.Color(204, 204, 255));
        reservar.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        reservar.setForeground(new java.awt.Color(255, 255, 255));
        reservar.setText("RESERVAR");
        reservar.setBorder(null);
        reservar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reservarActionPerformed(evt);
            }
        });
        getContentPane().add(reservar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 280, 100, 30));

        cp.setFont(new java.awt.Font("Segoe UI", 3, 21)); // NOI18N
        cp.setText("y");
        getContentPane().add(cp, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 180, 60, 40));
        getContentPane().add(imagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 140, 140));

        cpL.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        cpL.setText("CODIGO POSTAL:");
        getContentPane().add(cpL, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, -1, -1));

        nombreL.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        nombreL.setText("NOMBRE:");
        getContentPane().add(nombreL, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, -1, -1));
        getContentPane().add(ubicacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 160, 40, 40));

        ubicacionReal.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        ubicacionReal.setText("jLabel1");
        getContentPane().add(ubicacionReal, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 160, 110, 30));
        getContentPane().add(busqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, 360, 30));
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 760, 439));

        barraMenu.setBackground(new java.awt.Color(255, 204, 204));
        barraMenu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        menuBorrar.setBackground(new java.awt.Color(0, 0, 0));
        menuBorrar.setBorder(null);
        menuBorrar.setText("BORRAR");

        borrarReserva.setText("Borrar Reserva");
        menuBorrar.add(borrarReserva);

        borrar_reclamacion.setText("Borrar reclamacion");
        menuBorrar.add(borrar_reclamacion);

        barraMenu.add(menuBorrar);

        menuMod.setText("MODIFICAR");

        modReserva.setText("Modificar reserva");
        modReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modReservaActionPerformed(evt);
            }
        });
        menuMod.add(modReserva);

        barraMenu.add(menuMod);

        jMenu2.setText("VER");

        ver_reservas.setText("Ver reservas");
        ver_reservas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ver_reservasActionPerformed(evt);
            }
        });
        jMenu2.add(ver_reservas);

        ver_personal.setText("Ver personal");
        jMenu2.add(ver_personal);

        ver_reclamaciones.setText("Ver reclamaciones");
        jMenu2.add(ver_reclamaciones);

        barraMenu.add(jMenu2);

        insertar_mantenimiento.setText("INSERTAR");

        insertReclamacion.setText("Insertar Reclamación");
        insertar_mantenimiento.add(insertReclamacion);

        insertar_mantenimiento1.setText("Insertar Mantenimiento");
        insertar_mantenimiento.add(insertar_mantenimiento1);

        barraMenu.add(insertar_mantenimiento);

        setJMenuBar(barraMenu);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void reservarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reservarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_reservarActionPerformed

    private void modReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modReservaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modReservaActionPerformed

    private void ver_reservasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ver_reservasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ver_reservasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pantalla_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pantalla_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pantalla_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pantalla_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Pantalla_Principal().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(Pantalla_Principal.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IOException ex) {
                    Logger.getLogger(Pantalla_Principal.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar barraMenu;
    public static javax.swing.JMenuItem borrarReserva;
    private javax.swing.JMenuItem borrar_reclamacion;
    private interfaz.Busqueda busqueda;
    private javax.swing.JLabel cp;
    private javax.swing.JLabel cpL;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel imagen;
    private javax.swing.JMenuItem insertReclamacion;
    private javax.swing.JMenu insertar_mantenimiento;
    private javax.swing.JMenuItem insertar_mantenimiento1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenu menuBorrar;
    private javax.swing.JMenu menuMod;
    public static javax.swing.JMenuItem modReserva;
    private javax.swing.JLabel nombreHotel;
    private javax.swing.JLabel nombreL;
    private javax.swing.JButton reservar;
    private javax.swing.JLabel ubicacion;
    private javax.swing.JLabel ubicacionReal;
    private javax.swing.JMenuItem ver_personal;
    private javax.swing.JMenuItem ver_reclamaciones;
    private javax.swing.JMenuItem ver_reservas;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        if(e.getSource()==reservar){
            Reservar reser = new Reservar();
            reser.setVisible(true);
            
            this.setVisible(false);
            reser.dni_comp_Usu=dni_Usuario;
            reser.cp = cp.getText();
        }else if(e.getSource()==busqueda.buscar){
            try {
                cliente = new Socket("localhost",5555);
                DataInputStream dis = new DataInputStream(cliente.getInputStream()); 
                DataOutputStream dos = new DataOutputStream(cliente.getOutputStream()); 
                ObjectInputStream ois = new ObjectInputStream(cliente.getInputStream());
                
                dos.writeUTF("buscar_sucursal");
                dos.writeUTF(busqueda.busqueda.getText());
                
                JsonObject jso = jso=(JsonObject) ois.readObject();
                nombreHotel.setText((String) jso.get("nombre"));
                ubicacionReal.setText((String) jso.get("ciudad"));
                cp.setText((String) jso.get("codigo_postal"));
                
                String ruta=(String)jso.get("imagen");
                System.out.println("Contenido ruta: "+ruta);
                URL url = new URL(ruta);
                    fotoHotel = ImageIO.read(url);
                    imagen.setIcon(new ImageIcon(fotoHotel));
                imagen.setVisible(true);
                
                cp.setVisible(true);
                ubicacionReal.setVisible(true);
                nombreHotel.setVisible(true);
                cpL.setVisible(true);
                nombreL.setVisible(true);
                ubicacion.setVisible(true);
                
                reservar.setVisible(true);
                cliente.close();
                
            } catch (IOException ex) {
                Logger.getLogger(Pantalla_Principal.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(Pantalla_Principal.class.getName()).log(Level.SEVERE, null, ex);
            }
           
        }else if(e.getSource()==busqueda.buscarVoz){
            JOptionPane.showMessageDialog(this, "Este dispositivo no cuenta con un microfono para esta funcion.");
        
        }else if (e.getSource()==borrarReserva){
            this.setVisible(false);
            Borrar_Reserva borrar = new Borrar_Reserva();
            borrar.setVisible(true);
            
        }else if (e.getSource()==modReserva){
            this.setVisible(false);
            Modificar_Reserva mod = new Modificar_Reserva();
            mod.setVisible(true);
        }else if(e.getSource()==insertReclamacion){
            Insertar_Reclamacion r = new Insertar_Reclamacion();
            r.setVisible(true);
            this.setVisible(false);
        }else if(e.getSource()==ver_reclamaciones){
            Ver_Reclamaciones v = new Ver_Reclamaciones();
            v.setVisible(true);
            this.setVisible(false);
            
        }else if(e.getSource()==ver_personal){
            Ver_Personal v = new Ver_Personal();
            v.setVisible(true);
            this.setVisible(false);
            
        }else if(e.getSource()==ver_reservas){
            Ver_Reservas v = new Ver_Reservas();
            v.setVisible(true);
            this.setVisible(false);
            
        }else if(e.getSource()==borrar_reclamacion){
            Borrar_Reclamacion b = new Borrar_Reclamacion();
            b.setVisible(true);
            this.setVisible(false);
            
        }else if(e.getSource()==insertar_mantenimiento1){
            Insertar_Mantenimiento i = new Insertar_Mantenimiento();
            i.setVisible(true);
            this.setVisible(false);
        }
        
    }
}
